## نقرا الملف

In [51]:
import pandas as pd
dataset = pd.read_csv("iphone11.csv")
dataset
# purchase_iphone صفر يعني ما يقدر يشتري و الواحد يقدر يشتري

      gender  age  salary  purchase_iphone
0       Male   49  137858                1
1     Female   56   86235                1
2       Male   49   74240                0
3       Male   21  144019                1
4       Male   47   85726                1
...      ...  ...     ...              ...
1995  Female   31   80529                1
1996    Male   57   24207                1
1997  Female   57  122436                1
1998  Female   58  136434                1
1999  Female   61  138852                1

[2000 rows x 4 columns]

## راحح احدد اعمده الدخل و الخرج x and y

In [52]:
#لان هدفنا هو اعطي النموذج العمر و الراتب وهو يشوف يقدر يشتري ولا لا 
x = dataset.iloc[:,:-1].values
# لو كانت الاعمده كثيره صعب انك تكتب كل الاعمده فتكتب 
# x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3]
# تقدر تكتب بداله y= dataset.iloc[:,3]

## لازم نحول عمود الجنس الى ارقام يعني نرمزها (معالجه النصوص)

In [53]:
# عن طريق LabelEncoder داخله fit_transform
from sklearn.preprocessing import LabelEncoder

label_gender = LabelEncoder()

x[:,0] = label_gender.fit_transform(x[:,0])
x
# لو تلاحظ ان عمود الجنس صار ارقام

array([[1, 49, 137858],
       [0, 56, 86235],
       [1, 49, 74240],
       ...,
       [0, 57, 122436],
       [0, 58, 136434],
       [0, 61, 138852]], shape=(2000, 3), dtype=object)

## نقسم البيانات الى تدريب و اختبار

In [54]:
# راح تساعدنا train_test_split من model_selection 
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x , y , train_size = 0.8 , random_state = 0 )

## تقييس اليانات

In [55]:
dataset.describe()
# لو تلاحظ في فرق كبير بين الاعمده من min max

               age         salary  purchase_iphone
count  2000.000000    2000.000000      2000.000000
mean     40.910000   84875.747000         0.593000
std      13.549675   36747.417941         0.491398
min      18.000000   21150.000000         0.000000
25%      29.000000   52418.500000         0.000000
50%      41.000000   85378.000000         1.000000
75%      52.000000  116363.500000         1.000000
max      64.000000  147813.000000         1.000000

In [56]:
#  علشان نقرب قيم الاعمده ببعضها و النموذج يتوقع بشكل صحيح
# راح يساعدنا StandardScaler من preprocessing
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

## الان نستخدم gaussianNB من nive_bayes

In [57]:
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()

classifier.fit(x_train, y_train)

GaussianNB()

## الان نخليه يتنبئ

In [58]:
y_pred = classifier.predict(x_test)

## الان نقيم النموذج

In [59]:
from sklearn import metrics

cm = metrics.confusion_matrix(y_test, y_pred)

cm
#هاذي مصفوفه الارتباك  Tp , TN FP , FN

array([[ 74,  86],
       [ 39, 201]])

In [61]:
# نحسب accuracy 
accuracy = metrics.accuracy_score(y_test, y_pred)
print("the accuracy :", accuracy)
#نحسب precision 
precision = metrics.precision_score(y_test, y_pred)
print("the precision :", precision)
#نحسب recall
recall = metrics.recall_score(y_test, y_pred)
print("the recall :", recall)
# نلاحظ دقه تبنؤ النموذج 68

the accuracy : 0.6875
the precision : 0.7003484320557491
the recall : 0.8375

## الان نبي نحط الارقام وهو يتنبئ

In [63]:
#الحين نبي نسوي تنبؤ لبعض الاشخاص اذا بيشترون او لا 
#نبي نقيس البيانات ذي 
person1 = sc.transform([[1,21,40000]])
person2 = sc.transform([[1,41,80000]])
person3 = sc.transform([[0,41,400]])

print('male aged 21 making 40k$ will buy iphone:' , classifier.predict(person1))
#عطانا صفر يعني ما يقدر يشتري صاحب البيانات ذي

male aged 21 making 40k$ will buy iphone: [0]

In [66]:
print('male aged 41 making 80k$ will buy iphone:' , classifier.predict(person2))
print('female aged 41 making 400$ will buy iphone:' , classifier.predict(person3))

male aged 41 making 80k$ will buy iphone: [1]
female aged 41 making 400$ will buy iphone: [0]

## احصاء

In [69]:
# الان نبي نشوف احصائيه للشخص نسبه كم يشتري وما يشتري
print('male aged 21 making 40k$ will buy iphone:' , classifier.predict_proba(person1))
# احتمال انه يشتري 27بالميه

male aged 21 making 40k$ will buy iphone: [[0.7244626 0.2755374]]

In [70]:
print('male aged 41 making 80k$ will buy iphone:' , classifier.predict_proba(person2))

male aged 41 making 80k$ will buy iphone: [[0.41797791 0.58202209]]

In [71]:
print('female aged 41 making 400$ will buy iphone:' , classifier.predict_proba(person3))

female aged 41 making 400$ will buy iphone: [[0.73427631 0.26572369]]