## قرايه الملف

In [1]:
import pandas as pd 

dataset = pd.read_csv('iphone11.csv')

dataset

      gender  age  salary  purchase_iphone
0       Male   49  137858                1
1     Female   56   86235                1
2       Male   49   74240                0
3       Male   21  144019                1
4       Male   47   85726                1
...      ...  ...     ...              ...
1995  Female   31   80529                1
1996    Male   57   24207                1
1997  Female   57  122436                1
1998  Female   58  136434                1
1999  Female   61  138852                1

[2000 rows x 4 columns]

 ## راحح احدد اعمده الدخل و الخرج x and y

In [2]:
x = dataset.iloc[:,:-1].values
# لو كانت الاعمده كثيره صعب انك تكتب كل الاعمده فتكتب 
# x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3]
# تقدر تكتب بداله y= dataset.iloc[:,3]

## لازم نحول عمود الجنس الى ارقام يعني نرمزها (معالجه النصوص)

In [5]:
from sklearn.preprocessing import LabelEncoder

label_gender = LabelEncoder ()

x[:,0] = label_gender.fit_transform(x[:,0])

x

array([[1, 49, 137858],
       [0, 56, 86235],
       [1, 49, 74240],
       ...,
       [0, 57, 122436],
       [0, 58, 136434],
       [0, 61, 138852]], shape=(2000, 3), dtype=object)

## نقسم البيانات الى تدريب و اختبار

In [7]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x , y , train_size = 0.8 , random_state = 0 )

## تقييس اليانات

In [8]:
dataset.describe()
# لو تلاحظ في فرق كبير بين الاعمده من min max

               age         salary  purchase_iphone
count  2000.000000    2000.000000      2000.000000
mean     40.910000   84875.747000         0.593000
std      13.549675   36747.417941         0.491398
min      18.000000   21150.000000         0.000000
25%      29.000000   52418.500000         0.000000
50%      41.000000   85378.000000         1.000000
75%      52.000000  116363.500000         1.000000
max      64.000000  147813.000000         1.000000

In [12]:
from sklearn.preprocessing import StandardScaler 

sc =  StandardScaler()

x_train = sc.fit_transform(x_train )
x_test = sc.transform(x_test)

## الان راح نسوي المصنف decision tree

In [25]:
from sklearn.tree import DecisionTreeClassifier 
# تحدد المعامل انتروبي شرحناه في دفتر 
classifier = DecisionTreeClassifier( criterion = 'entropy' , random_state = 0 , max_depth=4 )
classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=0)

## الان نخليه يتنبئ

In [26]:
y_pred = classifier.predict(x_test)

##  نقيم النموذج

In [27]:
from sklearn import metrics 

cm = metrics.confusion_matrix(y_test, y_pred)

cm

array([[ 94,  66],
       [ 61, 179]])

In [28]:
# نحسب accuracy 
accuracy = metrics.accuracy_score(y_test, y_pred)
print("the accuracy :", accuracy)
#نحسب precision 
precision = metrics.precision_score(y_test, y_pred)
print("the precision :", precision)
#نحسب recall
recall = metrics.recall_score(y_test, y_pred)
print("the recall :", recall)
# دقه النموذج 57

the accuracy : 0.6825
the precision : 0.7306122448979592
the recall : 0.7458333333333333

## الان نبي نحط الارقام وهو يتنبئ

In [29]:
#الحين نبي نسوي تنبؤ لبعض الاشخاص اذا بيشترون او لا 
#نبي نقيس البيانات ذي 
person1 = sc.transform([[1,21,40000]])
person2 = sc.transform([[1,41,80000]])
person3 = sc.transform([[0,41,400]])

print('male aged 21 making 40k$ will buy iphone:' , classifier.predict(person1))
#عطانا صفر يعني ما يقدر يشتري صاحب البيانات ذي
print('male aged 41 making 80k$ will buy iphone:' , classifier.predict(person2))
print('female aged 41 making 400$ will buy iphone:' , classifier.predict(person3))

male aged 21 making 40k$ will buy iphone: [0]
male aged 41 making 80k$ will buy iphone: [1]
female aged 41 making 400$ will buy iphone: [0]

## احصاء

In [30]:
# الان نبي نشوف احصائيه للشخص نسبه كم يشتري وما يشتري
print('male aged 21 making 40k$ will buy iphone:' , classifier.predict_proba(person1))
print('male aged 41 making 80k$ will buy iphone:' , classifier.predict_proba(person2))
print('female aged 41 making 400$ will buy iphone:' , classifier.predict_proba(person3))
# في شجره القرار اذ طلع 0 1 يعني مارح يشتري اذا طلع العكس بيشتري

male aged 21 making 40k$ will buy iphone: [[0.70909091 0.29090909]]
male aged 41 making 80k$ will buy iphone: [[0.34666667 0.65333333]]
female aged 41 making 400$ will buy iphone: [[0.70909091 0.29090909]]