## قرايه الملف

In [1]:
import pandas as pd 

df = pd.read_csv('iphone11.csv')

df

      gender  age  salary  purchase_iphone
0       Male   49  137858                1
1     Female   56   86235                1
2       Male   49   74240                0
3       Male   21  144019                1
4       Male   47   85726                1
...      ...  ...     ...              ...
1995  Female   31   80529                1
1996    Male   57   24207                1
1997  Female   57  122436                1
1998  Female   58  136434                1
1999  Female   61  138852                1

[2000 rows x 4 columns]

## راح نحدد بيانات الدخل و الخرج

In [6]:
x = df.iloc[:,:-1].values
y = df.iloc[:,3]

## الان نبي نحول عمود الجنس الئ ارقام

In [8]:
from sklearn.preprocessing import LabelEncoder

labelencoder_gender = LabelEncoder()

x[: , 0] = labelencoder_gender.fit_transform( x[:, 0] )

## الان نحتاج تقييس البيانات

In [10]:
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler()
x = sc.fit_transform(x)
# لاحظ مارح نقسم بالطريقه العشوائي راح نسوي بالتقييم المتقاطع

In [53]:
from sklearn.model_selection import cross_val_score

# راح نسوي داله تقيم النماذج عن طريق التقيم المتقاطع
# يكتب النموذج و الدخل و الخرج  و cv 
# ثم يطلع قائمه تقييم النماذج الدقه 
def cv_comparison_classification( models , x , y ,cv):
    # نسوي اطار البيانات 
    cv_df = pd.DataFrame()
    # نسوي الحلقه يطلع الدقه و المتوسط 
    for model in models :
        acc = cross_val_score(model, x ,y ,scoring = 'accuracy',cv = cv )
        acc_avg = round(acc.mean() , 3)

        # نضيفها الى اطار البيانات
        cv_df[str(model)] = [acc_avg]
        cv_df.index = ['Accuracy']

    return cv_df

## الان نستدعي النماذج التصنيف

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm

mlr_d = DecisionTreeClassifier(criterion="entropy")

mlr_g = GaussianNB()

mlr_reg = LogisticRegression()

mlr_k = KNeighborsClassifier()

mlr_svc = svm.SVC(kernel="rbf")

models = [mlr_d, mlr_g, mlr_reg, mlr_k, mlr_svc]

models

[DecisionTreeClassifier(criterion='entropy'),
 GaussianNB(),
 LogisticRegression(),
 KNeighborsClassifier(),
 SVC()]

## الان نربطه مع الداله

In [58]:
comp_df = cv_comparison_classification(models, x , y , 10)
comp_df 
# لاحظ طلعنا لنا الدقه للنماذج التصنيف

,DecisionTreeClassifier(criterion='entropy'),GaussianNB(),LogisticRegression(),KNeighborsClassifier(),SVC()
Accuracy,0.587,0.667,0.668,0.632,0.663